services:

  devd:
    image: ghcr.io/jefftriplett/devd:latest
    command: ["--livewatch"]
    init: true
    ports:
      - 8000:8000
    volumes:
      - .:/srv/jekyll:cached

  jekyll:
    image: jekyll/jekyll:latest
    command: ["jekyll", "serve", "--host", "0.0.0.0", "--port", "4000", "--livereload", "--drafts", "--force_polling"]
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    expose:
      - 4000
    init: true
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:cached
      - ./.vendor/bundle:/usr/local/bundle:cached
